/* ============================================================================
   El Badry Transport — Arabic ⇄ English localization
   - Static content: elements carry data-i18n="key" (text), data-i18n-ph
     (placeholder), data-i18n-aria (aria-label). Parent elements that wrap
     icons use an inner <span data-i18n> so icons are never wiped.
   - document.title + meta[name=description] switch via site_title/meta_desc.
   - Choice persists in localStorage; <html lang dir> follow the language.
   - Dynamic strings elsewhere use window.t(key) with the js_* keys below.
   ============================================================================ */
(function () {
    'use strict';

    var I18N = {
        ar: {
            site_title: 'شركة البدري لنقل | شريكك الموثوق في النقل والشحن - خبرة +15 سنة',
            meta_desc: 'شركة البدري لنقل - خبرة أكثر من 15 سنة في النقل البري والشحن. نقل حاويات وصادر ووارد ونقل مبرد (سلسلة تبريد) مع ضمان سلامة المنقولات ومتابعة لحظية. اتصل: +201097304445',
            skip_link: 'تخطَّ إلى المحتوى الرئيسي',
            wa_float: 'تواصل معنا عبر واتساب',
            wa_tip: 'تواصل عبر واتساب',
            top_btn: 'العودة إلى أعلى الصفحة',
            logo_home: 'شركة البدري لنقل — الصفحة الرئيسية',
            brand_name: 'شركة البدري لنقل',
            brand_sub: 'El Badry Transport',
            nav_main: 'القائمة الرئيسية',
            nav_home: 'الرئيسية',
            nav_services: 'خدماتنا',
            nav_why: 'لماذا نحن',
            nav_how: 'كيف نعمل',
            nav_reviews: 'آراء العملاء',
            nav_contact: 'تواصل معنا',
            hero_eyebrow: 'شركة البدري لنقل — El Badry Transport',
            hero_title: 'شركة البدري لنقل — شريكك الموثوق في النقل والشحن',
            hero_sub: 'أكثر من 15 عاماً من الخبرة في النقل والشحن — نقل داخل وخارج الجمهورية، نقل حاويات وصادر ووارد، ونتعامل مع أكبر الموانئ والتوكيلات الملاحية والوكلاء على مستوى العالم.',
            hero_cta_quote: 'اطلب عرض سعر مجاني',
            hero_cta_call: 'اتصل بنا الآن',
            hero_cta_wa: 'واتساب',
            trust_1: 'خبرة أكثر من 15 سنة',
            trust_2: 'سمعة قوية وموثوقة',
            trust_3: 'شراكات مع أكبر التوكيلات الملاحية',
            trust_4: 'وكلاء معتمدون عالمياً',
            trust_5: 'تأمين شامل على الشحنات',
            trust_6: 'خدمة على مدار الساعة 24/24',
            hero_scroll: 'انتقل إلى قسم خدماتنا',
            sec_services_tag: 'خدماتنا',
            sec_services_title: 'خدمات متكاملة للنقل والشحن',
            sec_services_sub: 'من النقل المبرد إلى نقل الحاويات والصادر والوارد — كل ما تحتاجه تحت سقف واحد، بخبرة تتجاوز 15 عاماً.',
            svc_cold_title: 'النقل المبرد (سلسلة التبريد)',
            svc_cold_desc: 'شاحنات مبردة بأحدث أنظمة التبريد لنقل المواد الغذائية، اللحوم، الدواجن، المجمدات، والمنتجات الطازجة من المصدر حتى التسليم النهائي مع الحفاظ على سلسلة تبريد متكاملة.',
            svc_container_title: 'نقل الحاويات',
            svc_container_desc: 'نقل حاويات 20 و40 قدم من وإلى الموانئ المصرية بأحدث أسطول شاحنات مجهز.',
            svc_land_title: 'النقل البري',
            svc_land_desc: 'خدمات نقل بري للبضائع الثقيلة والخفيفة داخل وخارج الجمهورية بأمان تام.',
            svc_export_title: 'نقل الصادر',
            svc_export_desc: 'نقل شحنات التصدير من المصانع والمخازن إلى الموانئ بسرعة ودقة.',
            svc_import_title: 'نقل الوارد',
            svc_import_desc: 'استلام الحاويات من الموانئ وتوصيلها إلى وجهتها النهائية داخل مصر.',
            svc_tracking_title: 'تتبع الشحنات',
            svc_tracking_desc: 'نظام تتبع لحظي لشحنتك من لحظة التحميل حتى التسليم النهائي.',
            card_cta: 'اطلب الخدمة',
            svc_domestic_title: 'نقل داخل وخارج الجمهورية',
            svc_domestic_desc: 'تغطية شاملة لجميع محافظات مصر — من القاهرة والجيزة إلى الإسكندرية وأسوان والبحر الأحمر، بأسطول حديث ومتابعة لحظية.',
            why_tag: 'لماذا البدري؟',
            why_title: 'لماذا يثق بنا آلاف العملاء؟',
            why_sub: 'لا نبيع وعوداً — نبني سمعة منذ أكثر من 15 عاماً، شحنة بعد شحنة.',
            why_1_desc: 'خبرة أكثر من 15 سنة في مجال النقل والشحن المحلي والدولي. رأينا تطور السوق كله، وعلمنا كيف نتعامل مع كل نوع من الشحنات بأمانة واحترافية.',
            why_2_title: 'سمعة جبارة وقوية',
            why_2_desc: 'سمعة جبارة وقوية بُنيت على آلاف العملاء الراضين وثقتهم عبر السنين — نصائح عائلات وشركات ومنشآت تعود إلينا كل مرة، وتوصي بنا لغيرها.',
            why_3_title: 'نقل في جميع أنحاء الجمهورية',
            why_3_desc: 'نقل في جميع أنحاء الجمهورية — تغطية كاملة لكل المحافظات، من القاهرة والجيزة إلى الإسكندرية وأسوان والبحر الأحمر، ووصولاً إلى أبعد النقاط.',
            why_4_title: 'تعامل مع أكبر التوكيلات الملاحية',
            why_4_desc: 'تعامل مع أكبر التوكيلات الملاحية — شراكات رسمية مع كبرى شركات الملاحة والنقل البحري، تضمن لك أسعاراً تنافسية ومواعيد إبحار مؤكدة.',
            why_5_title: 'وكلاء معتمدون على مستوى العالم',
            why_5_desc: 'وكلاء معتمدون على مستوى العالم — شبكة عالمية تضمن وصول شحنتك لأي مكان بأمان، متابعة من باب إلى باب في القارات الأربع.',
            why_6_title: 'تأمين شامل + التزام بالمواعيد + خدمة 24/24',
            why_6_desc: 'تأمين شامل على الشحنات، التزام صارم بالمواعيد المتفق عليها، وخدمة عملاء على مدار 24 ساعة طوال أيام الأسبوع لراحة بالك التامة.',
            stats_aria: 'أرقام تتحدث عنا',
            stats_1: 'سنة خبرة',
            stats_2: 'عميل سعيد',
            stats_3: 'توكيل ملاحي ووكيل عالمي',
            stats_4: 'محافظة — تغطية داخل الجمهورية',
            steps_title: 'أربع خطوات تفصل شحنتك عن وجهتها',
            steps_sub: 'عملية واضحة وشفافة من أول اتصال حتى استلام الشحنة في الوجهة.',
            steps_1_a: 'عبر الهاتف أو واتساب:',
            steps_1_b: '— نرد عليك فوراً ونجيب على كل استفساراتك.',
            steps_2_title: 'معاينة وتقييم مجاني',
            steps_2_desc: 'عرض سعر شفاف ومفصل بدون أي رسوم مخفية، حسب حجم الشحنة والمسافة والخدمة المطلوبة.',
            steps_3_title: 'تحميل وتأمين الشحنة',
            steps_3_desc: 'تحميل الشحنة بأحدث المعدات وتربيطها وتأمينها جيداً لضمان ثباتها أثناء النقل، مع تجهيز الشاحنة أو الحاوية المناسبة لنوع البضاعة.',
            steps_4_title: 'التسليم والتتبع',
            steps_4_desc: 'تسليم الشحنة بأمان في الوجهة النهائية، مع تتبع لحظي من لحظة التحميل حتى التسليم وتأكيد الاستلام.',
            network_tag: 'شبكتنا العالمية',
            network_title: 'شبكة تمتد عبر القارات الأربع',
            network_desc: 'نتعامل مع أكبر التوكيلات الملاحية والوكلاء على مستوى العالم — شبكتنا تمتد عبر قارات آسيا وأوروبا وأفريقيا وأمريكا، لضمان وصول شحنتك إلى أي وجهة بأمان وفي موعدها.',
            network_1: 'شحن بحري بحاويات FCL و LCL',
            network_2: 'شحن جوي سريع عبر وكلاء معتمدين',
            network_3: 'تخليص جمركي ومتابعة مستندات كاملة',
            network_4: 'تأمين دولي على الشحنات',
            network_cta: 'اطلب عرض سعر للشحن الدولي',
            network_partners_title: 'شركاؤنا ووكلاؤنا',
            network_p1: 'خط ملاحى الميرسك',
            network_p2: 'سيراميكا كليوباترا',
            network_p3: 'دالتكس',
            network_p4: 'أجرين للحاصلات الزراعية',
            network_p5: 'محطة سوناك',
            network_p6: 'محطة نهضة مصر',
            network_more: 'والمزيد الكثير من الوكلاء والشركاء المعتمدين حول العالم',
            gallery_tag: 'معرض أعمالنا',
            gallery_title: 'أسطولنا في العمل',
            gallery_sub: 'من الميناء إلى باب منزلك — لحظات من يوم عملنا اليومي.',
            gallery_1: 'الشحن البحري من الميناء',
            gallery_2: 'نقل متعدد الوسائط',
            gallery_3: 'قافلة شاحنات جاهزة',
            gallery_4: 'أسطولنا في العمل',
            gallery_5: 'نقل البضائع بين المحافظات',
            gallery_6: 'رحلات نقل طويلة المدى',
            misc_lightbox: 'عارض الصور',
            misc_close: 'إغلاق الصورة',
            misc_prev: 'الصورة السابقة',
            misc_next: 'الصورة التالية',
            testi_tag: 'آراء عملائنا',
            testi_title: 'كلام الناس أهم من كلامنا',
            testi_sub: 'آراء حقيقية من عملاء اعتمدوا علينا في نقل بضائعهم وحاوياتهم وشحناتهم.',
            testi_stars: 'تقييم 5 من 5 نجوم',
            testi_1_text: '«تعاملت معاهم في نقل حاويات من ميناء الإسكندرية للمصنع. دقة في المواعيد وسيارات حديثة وتعامل احترافي.»',
            testi_1_name: 'أحمد محمود',
            testi_1_role: 'الإسكندرية — نقل حاويات',
            testi_2_text: '«شركة عندها خبرة حقيقية في نقل الصادر والوارد. نقلوا شحنة تصدير لميناء الدخيلة بدون أي تأخير.»',
            testi_2_name: 'محمد عبدالله',
            testi_2_role: 'القاهرة — نقل صادر',
            testi_3_text: '«بنتعامل معاهم بشكل دائم في نقل البضائع من وإلى الموانئ. أسطول قوي وأسعار منافسة وفريق محترم.»',
            testi_3_name: 'سارة إبراهيم',
            testi_3_role: 'الجيزة — نقل بضائع',
            pricing_tag: 'باقاتنا',
            pricing_title: 'اختر الباقة المناسبة لك',
            pricing_sub: 'أسعار نهائية تُحدد بعد المعاينة المجانية — والباقة تُعدّل حسب حجم الشحنة والمسافة.',
            pricing_1_name: 'باقة أساسية',
            pricing_1_sub: 'للانتقالات داخل المدينة',
            pricing_1_f1: 'نقل داخل المدينة',
            pricing_1_f2: 'شاحنات مغلقة أو مكشوفة حسب الشحنة',
            pricing_1_f3: 'تأمين أساسي على الشحنة',
            pricing_cta: 'اطلب الآن',
            pricing_badge: 'الأكثر طلباً',
            pricing_2_name: 'باقة متوسطة',
            pricing_2_sub: 'للانتقالات بين المحافظات',
            pricing_2_f1: 'نقل داخل الجمهورية',
            pricing_2_f2: 'شاحنات مبردة متاحة حسب الطلب',
            pricing_2_f3: 'تأمين شامل على الشحنة',
            pricing_2_f4: 'تتبع لحظي',
            pricing_3_name: 'باقة VIP',
            pricing_3_sub: 'للشحن الدولي والمنشآت الكبرى',
            pricing_3_f1: 'نقل حاويات صادر ووارد من وإلى الموانئ',
            pricing_3_f2: 'شاحنات مبردة لسلسلة التبريد الكاملة',
            pricing_3_f3: 'تأمين شامل + متابعة لحظية 24/7',
            pricing_3_f4: 'أولوية في المواعيد',
            contact_title: 'اطلب عرض سعر مجاني الآن',
            contact_sub: 'املأ البيانات وسنتواصل معك خلال ساعات العمل — أو اتصل بنا مباشرة في أي وقت.',
            contact_info_title: 'بيانات التواصل',
            contact_call_title: 'اتصل بنا',
            contact_wa_cta: 'اضغط لبدء المحادثة الآن',
            contact_email_title: 'البريد الإلكتروني',
            contact_email_desc: '— بريد الشركة',
            contact_addr_title: 'العنوان',
            contact_addr: 'شارع مرور العجمى طريق ام زغيو امام بوابه عز الدخيله — الاسكندرية، مصر',
            contact_hours_title: 'مواعيد العمل',
            contact_hours_1: 'على مدار الساعة',
            contact_hours_2: 'خدمة طوارئ 24/24',
            form_name_label: 'الاسم بالكامل',
            form_name_ph: 'مثال: أحمد محمد علي',
            form_phone_label: 'رقم الهاتف',
            form_city_label: 'المدينة / المنطقة',
            form_city_ph: 'مثال: القاهرة — مدينة نصر',
            form_service_label: 'نوع الخدمة',
            form_service_default: '— اختر نوع الخدمة —',
            form_svc_container: 'نقل حاويات',
            form_svc_land: 'نقل بري',
            form_svc_export: 'نقل صادر',
            form_svc_import: 'نقل وارد',
            form_svc_cold: 'النقل المبرد (سلسلة التبريد)',
            form_svc_domestic: 'نقل داخل وخارج الجمهورية',
            form_svc_other: 'أخرى',
            form_details_label: 'تفاصيل إضافية',
            form_details_ph: 'اكتب تفاصيل الشحنة، المسافة، الموعد المفضل، أو أي متطلبات خاصة...',
            form_submit: 'أرسل الطلب',
            form_note: 'بياناتك آمنة لدىنا ولن تُستخدم إلا للتواصل بخصوص طلبك.',
            map_link: 'عرض الخريطة التفاعلية',
            footer_about: 'خبرة أكثر من 15 عاماً في النقل البري والشحن — نقل حاويات وصادر ووارد ونقل مبرد (سلسلة تبريد) للمنشآت والمصانع — ونتعامل مع أكبر التوكيلات الملاحية والوكلاء حول العالم.',
            footer_quick_title: 'روابط سريعة',
            footer_wa: 'واتساب مباشر',
            footer_email: '— البريد',
            footer_hours: 'على مدار الساعة 24/24',
            footer_fb_live: 'فيسبوك',
            footer_ig: 'صفحة إنستغرام (قريباً)',
            footer_tt: 'حساب تيك توك (قريباً)',
            footer_rights_body: 'شركة البدري لنقل — جميع الحقوق محفوظة',
            js_gallery_zoom: 'تكبير الصورة: ',
            js_val_name_required: 'من فضلك أدخل الاسم بالكامل',
            js_val_name_short: 'الاسم قصير جداً — 3 أحرف على الأقل',
            js_val_name_letters: 'الاسم يجب أن يحتوي على حروف فقط',
            js_val_phone_required: 'من فضلك أدخل رقم الهاتف',
            js_val_phone_invalid: 'رقم غير صحيح — أدخل رقم مصري مكون من 11 رقماً يبدأ بـ 01',
            js_val_service_required: 'من فضلك اختر نوع الخدمة',
            js_form_fix_errors: 'من فضلك راجع الحقول المطلوبة بالأحمر.',
            js_form_sending: 'جارٍ الإرسال...',
            js_form_send: 'أرسل الطلب',
            js_wa_title: 'طلب عرض سعر جديد من الموقع:',
            js_wa_name: 'الاسم: ',
            js_wa_phone: 'الهاتف: ',
            js_wa_city: 'المدينة: ',
            js_wa_service: 'الخدمة: ',
            js_wa_details: 'تفاصيل: ',
            js_wa_ready: 'تم تجهيز طلبك في واتساب — اضغط إرسال هناك لإتمامه، وسيتواصل معك فريقنا.',
            js_form_sent: '✅ تم إرسال طلبك بنجاح! سيتواصل معك فريقنا قريباً.',
            js_form_fail: 'تعذّر إرسال الطلب — من فضلك حاول مرة أخرى أو اتصل: 01097304445',
            js_form_offline: 'تعذّر الاتصال بالخادم — يرجى المحاولة مجدداً أو الاتصال: 01097304445',
            js_social_soon: 'قريباً — صفحة ',
            js_social_soon_b: 'التواصل الاجتماعي',
            js_social_soon_c: ' (قريباً)',
            js_social_todo: ' قيد الإنشاء'
        },
        en: {
            site_title: 'El Badry Transport | Your Trusted Freight & Shipping Partner - 15+ Years',
            meta_desc: 'El Badry Transport - 15+ years of land transport and freight experience. Container, export, import, and refrigerated (cold chain) trucking with cargo safety and live tracking. Call: +201097304445',
            skip_link: 'Skip to main content',
            wa_float: 'Chat with us on WhatsApp',
            wa_tip: 'Chat on WhatsApp',
            top_btn: 'Back to top',
            logo_home: 'El Badry Transport — Home page',
            brand_name: 'El Badry Transport',
            brand_sub: 'شركة البدري لنقل',
            nav_main: 'Main menu',
            nav_home: 'Home',
            nav_services: 'Services',
            nav_why: 'Why Us',
            nav_how: 'How We Work',
            nav_reviews: 'Reviews',
            nav_contact: 'Contact Us',
            hero_eyebrow: 'El Badry Transport Company',
            hero_title: 'El Badry Transport — Your Trusted Freight & Shipping Partner',
            hero_sub: 'Land freight across Egypt — containers, exports, and imports — partnered with Egypt\u2019s major ports, shipping agencies, and global agents.',
            hero_cta_quote: 'Get a Free Quote',
            hero_cta_call: 'Call Us Now',
            hero_cta_wa: 'WhatsApp',
            trust_1: '15+ years of experience',
            trust_2: 'Strong, trusted reputation',
            trust_3: 'Partnerships with major shipping lines',
            trust_4: 'Worldwide certified agents',
            trust_5: 'Full cargo insurance',
            trust_6: '24/24 service',
            hero_scroll: 'Go to our services',
            sec_services_tag: 'Our Services',
            sec_services_title: 'Integrated Freight & Shipping Services',
            sec_services_sub: 'From refrigerated transport to container haulage, export, and import — everything you need under one roof, with 15+ years of experience.',
            svc_cold_title: 'Refrigerated Transport (Cold Chain)',
            svc_cold_desc: 'Modern refrigerated trucks for food, meat, poultry, frozen goods, and fresh produce — full cold chain maintained from origin to final delivery.',
            svc_container_title: 'Container Transport',
            svc_container_desc: '20ft and 40ft container haulage to and from Egyptian ports with a modern equipped fleet.',
            svc_land_title: 'Land Freight Transport',
            svc_land_desc: 'Heavy and light cargo trucking across Egypt with full safety standards.',
            svc_export_title: 'Export Trucking',
            svc_export_desc: 'Fast, precise haulage of export shipments from factories and warehouses to ports.',
            svc_import_title: 'Import Trucking',
            svc_import_desc: 'Container pickup from ports and delivery to final destinations across Egypt.',
            svc_tracking_title: 'Shipment Tracking',
            svc_tracking_desc: 'Real-time tracking from loading to final delivery.',
            card_cta: 'Request Service',
            svc_domestic_title: 'Domestic & Nationwide Transport',
            svc_domestic_desc: 'Full coverage across Egypt — from Cairo and Giza to Alexandria, Aswan, and the Red Sea — with a modern fleet and live tracking.',
            why_tag: 'Why El Badry?',
            why_title: 'Why Do Thousands of Customers Trust Us?',
            why_sub: 'We don\u2019t sell promises — we\u2019ve built a reputation for 15+ years, shipment after shipment.',
            why_1_desc: '15+ years in local and international transport and shipping. We\u2019ve watched the whole market evolve, and learned to handle every shipment type honestly and professionally.',
            why_2_title: 'A Huge, Strong Reputation',
            why_2_desc: 'A huge, strong reputation built on thousands of satisfied customers and their trust over the years — families, companies, and facilities that come back every time and recommend us to others.',
            why_3_title: 'Transport Across the Country',
            why_3_desc: 'Transport across the country — full coverage of every governorate, from Cairo and Giza to Alexandria, Aswan, and the Red Sea, reaching the farthest points.',
            why_4_title: 'Dealing With Major Shipping Lines',
            why_4_desc: 'Dealing with major shipping lines — official partnerships with top maritime and sea-freight companies, guaranteeing competitive prices and confirmed sailing dates.',
            why_5_title: 'Certified Agents Worldwide',
            why_5_desc: 'Certified agents worldwide — a global network ensuring your shipment reaches anywhere safely, tracked door to door across four continents.',
            why_6_title: 'Full Insurance + On-Time + 24/24 Service',
            why_6_desc: 'Full shipment insurance, strict commitment to agreed dates, and 24/24 customer service for total peace of mind.',
            stats_aria: 'Numbers that speak for us',
            stats_1: 'Years of experience',
            stats_2: 'Happy clients',
            stats_3: 'Shipping lines & global agents',
            stats_4: 'Governorates — coverage across the country',
            steps_title: 'Four Steps Between Your Shipment and Its Destination',
            steps_sub: 'A clear, transparent process from the first call to delivery at the destination.',
            steps_1_a: 'By phone or WhatsApp:',
            steps_1_b: '— we reply immediately and answer all your questions.',
            steps_2_title: 'Free Inspection & Assessment',
            steps_2_desc: 'A transparent, detailed quote with no hidden fees, based on shipment size, distance, and required service.',
            steps_3_title: 'Loading & Securing',
            steps_3_desc: 'Loading your cargo with modern equipment — careful lashing and securing to keep it stable in transit, with the right truck or container matched to your goods.',
            steps_4_title: 'Delivery & Tracking',
            steps_4_desc: 'Safe delivery to the final destination, with live tracking from loading to handover and confirmed receipt.',
            network_tag: 'Our Global Network',
            network_title: 'A Network Across Four Continents',
            network_desc: 'We deal with the largest shipping lines and agents worldwide — our network spans Asia, Europe, Africa, and America to get your shipment anywhere safely and on time.',
            network_1: 'Sea freight in FCL & LCL containers',
            network_2: 'Fast air freight via certified agents',
            network_3: 'Full customs clearance & paperwork follow-up',
            network_4: 'International shipment insurance',
            network_cta: 'Request an International Shipping Quote',
            network_partners_title: 'Our Partners & Agents',
            network_p1: 'Maersk Shipping Line',
            network_p2: 'Cleopatra Ceramics',
            network_p3: 'Daltex',
            network_p4: 'Agreen for Agricultural Produce',
            network_p5: 'Sonak Terminal',
            network_p6: 'Nahda Misr Terminal',
            network_more: 'Plus many more certified agents and partners worldwide',
            gallery_tag: 'Our Work Gallery',
            gallery_title: 'Our Fleet in Action',
            gallery_sub: 'From the port to your door — moments from our daily work.',
            gallery_1: 'Sea freight from the port',
            gallery_2: 'Multimodal transport',
            gallery_3: 'Truck convoy ready to go',
            gallery_4: 'Our fleet at work',
            gallery_5: 'Transporting goods between governorates',
            gallery_6: 'Long-haul journeys',
            misc_lightbox: 'Image viewer',
            misc_close: 'Close image',
            misc_prev: 'Previous image',
            misc_next: 'Next image',
            testi_tag: 'Our Clients\u2019 Reviews',
            testi_title: 'People\u2019s Words Matter More Than Ours',
            testi_sub: 'Real reviews from clients who trusted us with their cargo, containers, and shipments.',
            testi_stars: 'Rated 5 out of 5 stars',
            testi_1_text: '“I worked with them transporting containers from Alexandria port to the factory. On-time precision, modern trucks, and professional dealing.”',
            testi_1_name: 'Ahmed Mahmoud',
            testi_1_role: 'Alexandria — Container transport',
            testi_2_text: '“A company with real export and import trucking experience. They hauled an export shipment to Dekheila port with zero delays.”',
            testi_2_name: 'Mohamed Abdullah',
            testi_2_role: 'Cairo — Export trucking',
            testi_3_text: '“We work with them regularly transporting goods to and from the ports. Strong fleet, competitive prices, and a respectful team.”',
            testi_3_name: 'Sarah Ibrahim',
            testi_3_role: 'Giza — Cargo transport',
            pricing_tag: 'Our Packages',
            pricing_title: 'Choose the Right Package',
            pricing_sub: 'Final prices are set after the free inspection — packages adjust to shipment size and distance.',
            pricing_1_name: 'Basic Package',
            pricing_1_sub: 'For moves within the city',
            pricing_1_f1: 'In-city transport',
            pricing_1_f2: 'Closed or open trucks to suit the cargo',
            pricing_1_f3: 'Basic cargo insurance',
            pricing_cta: 'Order Now',
            pricing_badge: 'Most Requested',
            pricing_2_name: 'Standard Package',
            pricing_2_sub: 'For inter-governorate moves',
            pricing_2_f1: 'Nationwide transport across Egypt',
            pricing_2_f2: 'Refrigerated trucks available on request',
            pricing_2_f3: 'Full cargo insurance',
            pricing_2_f4: 'Live shipment tracking',
            pricing_3_name: 'VIP Package',
            pricing_3_sub: 'For international shipping & large facilities',
            pricing_3_f1: 'Import & export container transport to and from ports',
            pricing_3_f2: 'Refrigerated trucks for a complete cold chain',
            pricing_3_f3: 'Full insurance + 24/7 live monitoring',
            pricing_3_f4: 'Priority scheduling',
            contact_title: 'Request Your Free Quote Now',
            contact_sub: 'Fill in the details and we\u2019ll contact you during working hours — or call us directly anytime.',
            contact_info_title: 'Contact Information',
            contact_call_title: 'Call Us',
            contact_wa_cta: 'Tap to start chatting now',
            contact_email_title: 'Email',
            contact_email_desc: '— Company email',
            contact_addr_title: 'Address',
            contact_addr: 'El-Agamy Traffic St., Om Zegheo Rd, in front of Ezz El-Dekheila Gate — Alexandria, Egypt',
            contact_hours_title: 'Working Hours',
            contact_hours_1: 'Around the clock',
            contact_hours_2: '24/24 emergency service',
            form_name_label: 'Full Name',
            form_name_ph: 'e.g. Ahmed Mohamed Ali',
            form_phone_label: 'Phone Number',
            form_city_label: 'City / Area',
            form_city_ph: 'e.g. Cairo — Nasr City',
            form_service_label: 'Service Type',
            form_service_default: '— Select a service —',
            form_svc_container: 'Container transport',
            form_svc_land: 'Land freight',
            form_svc_export: 'Export trucking',
            form_svc_import: 'Import trucking',
            form_svc_cold: 'Refrigerated (Cold Chain)',
            form_svc_domestic: 'Domestic & Nationwide Transport',
            form_svc_other: 'Other',
            form_details_label: 'Extra Details',
            form_details_ph: 'Write shipment details, distance, preferred date, or any special requirements...',
            form_submit: 'Send Request',
            form_note: 'Your data is safe with us and will only be used to contact you about your request.',
            map_link: 'View Interactive Map',
            footer_about: '15+ years of land transport and freight experience — container, export, import, and refrigerated (cold chain) trucking for facilities and factories — working with the largest shipping lines and agents worldwide.',
            footer_quick_title: 'Quick Links',
            footer_wa: 'Direct WhatsApp',
            footer_email: 'Email',
            footer_hours: '24/24 around the clock',
            footer_fb_live: 'Facebook',
            footer_ig: 'Instagram page (soon)',
            footer_tt: 'TikTok account (soon)',
            footer_rights_body: 'El Badry Transport Company — All rights reserved',
            js_gallery_zoom: 'Enlarge image: ',
            js_val_name_required: 'Please enter your full name',
            js_val_name_short: 'Name is too short — at least 3 characters',
            js_val_name_letters: 'Name must contain letters only',
            js_val_phone_required: 'Please enter your phone number',
            js_val_phone_invalid: 'Invalid number — enter an 11-digit Egyptian number starting with 01',
            js_val_service_required: 'Please select a service type',
            js_form_fix_errors: 'Please review the required fields in red.',
            js_form_sending: 'Sending...',
            js_form_send: 'Send Request',
            js_wa_title: 'New quote request from the website:',
            js_wa_name: 'Name: ',
            js_wa_phone: 'Phone: ',
            js_wa_city: 'City: ',
            js_wa_service: 'Service: ',
            js_wa_details: 'Details: ',
            js_wa_ready: 'Your request is ready in WhatsApp — press send there to complete it, and our team will contact you.',
            js_form_sent: '✅ Your request was sent successfully! Our team will contact you soon.',
            js_form_fail: 'Could not send your request — please try again or call: 01097304445',
            js_form_offline: 'Could not reach the server — please try again or call: 01097304445',
            js_social_soon: 'Coming soon — ',
            js_social_soon_b: ' page',
            js_social_soon_c: ' (soon)',
            js_social_todo: ' under construction'
        }
    };

    var LANG_KEY = 'elbadry-lang';
    var lang = 'ar';
    try { lang = localStorage.getItem(LANG_KEY) || 'ar'; } catch (e) { lang = 'ar'; }
    if (lang !== 'ar' && lang !== 'en') lang = 'ar';

    function t(key) {
        var dict = I18N[lang] || I18N.ar;
        if (dict[key] !== undefined) return dict[key];
        if (I18N.ar[key] !== undefined) return I18N.ar[key];
        return key;
    }

    function applyI18n() {
        var dict = I18N[lang] || I18N.ar;
        document.querySelectorAll('[data-i18n]').forEach(function (el) {
            var key = el.getAttribute('data-i18n');
            if (dict[key] !== undefined) el.textContent = dict[key];
        });
        document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
            var key = el.getAttribute('data-i18n-ph');
            if (dict[key] !== undefined) el.setAttribute('placeholder', dict[key]);
        });
        document.querySelectorAll('[data-i18n-aria]').forEach(function (el) {
            var key = el.getAttribute('data-i18n-aria');
            if (dict[key] !== undefined) el.setAttribute('aria-label', dict[key]);
        });
        document.title = t('site_title');
        var meta = document.querySelector('meta[name="description"]');
        if (meta) meta.setAttribute('content', t('meta_desc'));
        document.documentElement.lang = lang;
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        var label = document.getElementById('lang-label');
        if (label) label.textContent = lang === 'ar' ? 'EN' : 'عربي';
        var toggle = document.getElementById('lang-toggle');
        if (toggle) toggle.setAttribute('aria-label', lang === 'ar' ? 'Switch to English' : 'التبديل إلى العربية');
        try { localStorage.setItem(LANG_KEY, lang); } catch (e) {}
        document.dispatchEvent(new CustomEvent('langchange'));
    }

    function setLang(next) {
        lang = (next === 'en') ? 'en' : 'ar';
        applyI18n();
    }

    function initLang() {
        applyI18n();
        var toggle = document.getElementById('lang-toggle');
        if (toggle) toggle.addEventListener('click', function () {
            setLang(lang === 'ar' ? 'en' : 'ar');
        });
    }

    window.__i18n = { t: t, setLang: setLang, getLang: function () { return lang; }, apply: applyI18n };
    window.t = window.t || t;
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initLang);
    } else {
        initLang();
    }
})();
